#!/bin/bash

# JankyBorders configuration script
# Placed under ~/dotfiles/borders/bordersrc

options=(
    style=round
    width=6.0
    active_color=0xffe6c384       # Kanagawa Dragon Yellow
    inactive_color=0xff2a2a37     # Kanagawa Sumi Ink 4 (subtle dark border)
    background_color=0x30000000   # Subtle background shadow
    hidpi=on                      # Enable HiDPI support
)

borders "${options[@]}"
